#pragma once


#warning "SHA1 algorithm implementation should not be used under ANY circumstances crytographic purposes."
#include <array>
#include <cstdint>

using shatype = std::array<std::uint8_t, 20>;


#include <bit>


// Code generated by chatgpt v5
// Prompt: write a constexpr uuidv5 algorithm

constexpr shatype sha1(const std::uint8_t *data, const std::size_t len)
    {
        std::uint32_t h0 = 0x67452301;
        std::uint32_t h1 = 0xEFCDAB89;
        std::uint32_t h2 = 0x98BADCFE;
        std::uint32_t h3 = 0x10325476;
        std::uint32_t h4 = 0xC3D2E1F0;

        std::array<std::uint8_t, 64> block{};
        std::size_t offset = 0;

        auto process_block = [&](const std::uint8_t* b)
        {
            std::uint32_t w[80]{};

            for (int i = 0; i < 16; ++i)
            {
                w[i] =
                    (std::uint32_t(b[i * 4 + 0]) << 24) |
                    (std::uint32_t(b[i * 4 + 1]) << 16) |
                    (std::uint32_t(b[i * 4 + 2]) <<  8) |
                    (std::uint32_t(b[i * 4 + 3]) <<  0);
            }

            for (int i = 16; i < 80; ++i)
                w[i] = std::rotl(w[i - 3] ^ w[i - 8] ^ w[i - 14] ^ w[i - 16], 1);

            std::uint32_t a = h0, b_ = h1, c = h2, d = h3, e = h4;

            for (int i = 0; i < 80; ++i)
            {
                std::uint32_t f, k;

                if (i < 20)      { f = (b_ & c) | (~b_ & d); k = 0x5A827999; }
                else if (i < 40) { f = b_ ^ c ^ d;          k = 0x6ED9EBA1; }
                else if (i < 60) { f = (b_ & c) | (b_ & d) | (c & d); k = 0x8F1BBCDC; }
                else             { f = b_ ^ c ^ d;          k = 0xCA62C1D6; }

                auto temp = std::rotl(a, 5) + f + e + k + w[i];
                e = d;
                d = c;
                c = std::rotl(b_, 30);
                b_ = a;
                a = temp;
            }

            h0 += a;
            h1 += b_;
            h2 += c;
            h3 += d;
            h4 += e;
        };

        // Process full blocks
        while (len - offset >= 64)
        {
            for (int i = 0; i < 64; ++i)
                block[i] = data[offset + i];
            process_block(block.data());
            offset += 64;
        }

        // Padding
        std::size_t rem = len - offset;
        for (std::size_t i = 0; i < rem; ++i)
            block[i] = data[offset + i];

        block[rem] = std::uint8_t(0x80);
        for (std::size_t i = rem + 1; i < 64; ++i)
            block[i] = std::uint8_t(0);

        if (rem >= 56)
        {
            process_block(block.data());
            for (auto& b : block) b = std::uint8_t(0);
        }

        std::uint64_t bit_len = len * 8;
        for (int i = 0; i < 8; ++i)
            block[63 - i] = std::uint8_t(bit_len >> (i * 8));

        process_block(block.data());

        shatype digest{};
        std::uint32_t hs[5]{ h0, h1, h2, h3, h4 };

        for (int i = 0; i < 5; ++i)
        {
            digest[i * 4 + 0] = std::uint8_t(hs[i] >> 24);
            digest[i * 4 + 1] = std::uint8_t(hs[i] >> 16);
            digest[i * 4 + 2] = std::uint8_t(hs[i] >> 8);
            digest[i * 4 + 3] = std::uint8_t(hs[i]);
        }

        return digest;
    }
